### ISSUE TITLE
ImportWarning on 3.6+

### ISSUE THREAD

**Issue by tjstum** [tkluck/accumulation_tree#2]
Trying to import this package on newer versions of python triggers the following warning (which can become an error):
```
$ python -Werror -c 'import accumulation_tree'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/stum/test36/lib/python3.6/site-packages/accumulation_tree/__init__.py", line 2, in <module>
    from .accumulation_tree import AccumulationTree
  File "accumulation_tree/accumulation_tree.pyx", line 2, in init accumulation_tree.accumulation_tree
ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
```

I've replicated this behavior on 3.6.10, 3.7.6 and 3.8.2 on both mac and linux. I just installed using `pip install accumulation_tree`

I've found cython/cython#1720 and cython/cython#1753, which suggest that adding `from __future__ import absolute_import` can resolve this... The only problem is that accumulation_tree already includes that code, and yet it still triggers that warning.
The other suggestion on those issues is to cythonize the extension with language_level=3. I can confirm that adding `# cython: language_level=3` to the top of `accumulation_tree.pyx` or changing the setup.py incantation to use `cythonize(..., language_level="3")` solve the problem. 

I'm not totally sure what the plans for version support or use of `cythonize` are for this module, so I didn't just want to send an unsolicited PR. I can if you'd like, though!

**Comment by tkluck** [comment]
Thanks for reporting the issue! Adding the version directive at the top of the file sounds good and I'll gladly merge a PR for that.

**Comment by tjstum** [comment]
I've been digging into this further in order to try to write a test case for this, and I'm now perplexed. I'm not consistently reproducing it.

The test case is, again, `python -Werror -c 'import accumulation_Tree'` after installing.

Fails:
- `pip install --no-cache accumulation_tree`
- `pip wheel accumulation_tree` followed by `pip install`ing that wheel
- downloading the `.tar..gz` from [pypi](https://pypi.org/project/accumulation-tree/#files) and running `setup.py` in that

Passes:
- running `setup.py install` in an unmodified clone of this repo
- building a wheel from sources `setup.py bdist_wheel` then installing that

So it seems that it's somehow related to the last upload to pypi. Given that I don't have a way to reproduce this from just the raw source, I'm less convinced that my suggested fix is necessary. I wonder if just bumping the version number to `0.6.1` and reuploading would fix this problem.

For the issue I was trying to solve, building my own wheel from sources instead of using PyPI works. I'm happy to help test if you want, or we can just close this.

**Comment by tkluck** [comment]
I just did a new upload to pypi, but it still gives the same issue as far as I can tell. It looks like `python3 setup.py sdist` builds a source distribution that has this issue, where just a direct install doesn't. I'll debug a bit more.

**Comment by tkluck** [comment]
It looks like I was able to resolve this by just re-cythonizing the source file. Would you mind checking whether the current version on PyPI (0.6.2) works for you?

**Comment by tjstum** [comment]
Yeah, as far as I can tell, this fixes the issue!

Love it when a recompile just fixes it! Thanks.
