### ISSUE TITLE
The latest version doesn't work on Windows

### ISSUE THREAD

**Issue by alexey-stankevich** [tkluck/accumulation_tree#3]
Hello, 

With Python 2.7.16 on Windows the following code

```python
from accumulation_tree import AccumulationTree
t = AccumulationTree(lambda x: x)
t.insert(1, 1)
```
fails with this error:

```
Traceback (most recent call last):
  File "D:\app\scripts\--TMP--\test.py", line 3, in <module>
    t.insert(1, 1)
  File "accumulation_tree\\accumulation_tree.pyx", line 233, in accumulation_tree.accumulation_tree._AccumulationTree.insert
TypeError: unbound method cython_function_or_method object must be called with RBTree instance as first argument (got AccumulationTree instance instead)
```

On macOS, it works fine with the same Python version.

**Comment by tkluck** [comment]
Thanks for reporting the issue @alexey-stankevich . Is this something you can reproduce with a supported version of python?

**Comment by alexey-stankevich** [comment]
It does work with python 3.8.3 and doesn't work with python 2.7.18.

**Comment by alexey-stankevich** [comment]
It seems I've found the issue. For some reason files in tar.gz don't have modification time, and Windows set it to 01/01/1970. This triggers weird python behavior when trying to build a wheel.

When I changed timestamps, the issue disappeared.

**Comment by tkluck** [comment]
Wow, that's very odd. Thanks for finding the issue and documenting it here!
