### ISSUE TITLE
install

### ISSUE THREAD

**Issue by microprediction** [tkluck/accumulation_tree#4]
reating build/temp.linux-x86_64-3.7/accumulation_tree
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/nfs/i1/c/home/peter/virtual-envs/optim/include -I/usr/include/python3.7m -c accumulation_tree/accumulation_tree.c -o build/temp.linux-x86_64-3.7/accumulation_tree/accumulation_tree.o
  accumulation_tree/accumulation_tree.c:4:10: fatal error: Python.h: No such file or directory
   #include "Python.h"
            ^~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by tkluck** [comment]
This looks like it can be solved by
```
apt install libpython3-dev
```
or the corresponding command on your distribution.
