### ISSUE TITLE
Accumulation Tree causing build error

### ISSUE THREAD

**Issue by csrajath** [tkluck/accumulation_tree#5]
How can I go about the same?

`
Building wheels for collected packages: hurry.filesize, accumulation-tree, pyudorandom
  Building wheel for hurry.filesize (setup.py) ... done
  Created wheel for hurry.filesize: filename=hurry.filesize-0.9-py3-none-any.whl size=4140 sha256=f58e0be472b8270b98a1486e1b30122257820fa20d5cfe4b52a4455588d7b1c7
  Stored in directory: c:\users\ipl\appdata\local\pip\cache\wheels\28\4e\4f\de74e961eaf2cc15974f0d7a9c73515860843923bd3700bee6
  Building wheel for accumulation-tree (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\IPL\anaconda3\envs\flare_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\IPL\\AppData\\Local\\Temp\\pip-install-swpip_rv\\accumulation-tree\\setup.py'"'"'; __file__='"'"'C:\\Users\\IPL\\AppData\\Local\\Temp\\pip-install-swpip_rv\\accumulation-tree\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\IPL\AppData\Local\Temp\pip-wheel-gvfw3da2'
       cwd: C:\Users\IPL\AppData\Local\Temp\pip-install-swpip_rv\accumulation-tree\
  Complete output (15 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\accumulation_tree
  copying accumulation_tree\abctree.py -> build\lib.win-amd64-3.6\accumulation_tree
  copying accumulation_tree\treeslice.py -> build\lib.win-amd64-3.6\accumulation_tree
  copying accumulation_tree\__init__.py -> build\lib.win-amd64-3.6\accumulation_tree
  running build_ext
  cythoning accumulation_tree/accumulation_tree.pyx to accumulation_tree\accumulation_tree.c
  c:\users\ipl\appdata\local\temp\pip-install-swpip_rv\accumulation-tree\.eggs\cython-0.29.21-py3.6-win-amd64.egg\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\IPL\AppData\Local\Temp\pip-install-swpip_rv\accumulation-tree\accumulation_tree\accumulation_tree.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'accumulation_tree.accumulation_tree' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

  ERROR: Failed building wheel for accumulation-tree
  Running setup.py clean for accumulation-tree
  Building wheel for pyudorandom (setup.py) ... done
  Created wheel for pyudorandom: filename=pyudorandom-1.0.0-py3-none-any.whl size=2230 sha256=86f94b46021772593ca4191830581ae6e1fd07b836aca6768ac5ecdbbb3eb246
  Stored in directory: c:\users\ipl\appdata\local\pip\cache\wheels\6a\1c\44\a36680940ed50318768af5bd3d414088188e90179ad33c8a45
Successfully built hurry.filesize pyudorandom
Failed to build accumulation-tree
Installing collected packages: hurry.filesize, accumulation-tree, pyudorandom, tdigest, mvtsdatatoolkit
    Running setup.py install for accumulation-tree ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\IPL\anaconda3\envs\flare_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\IPL\\AppData\\Local\\Temp\\pip-install-swpip_rv\\accumulation-tree\\setup.py'"'"'; __file__='"'"'C:\\Users\\IPL\\AppData\\Local\\Temp\\pip-install-swpip_rv\\accumulation-tree\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\IPL\AppData\Local\Temp\pip-record-67vct1pd\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\IPL\anaconda3\envs\flare_env\Include\accumulation-tree'
         cwd: C:\Users\IPL\AppData\Local\Temp\pip-install-swpip_rv\accumulation-tree\
    Complete output (13 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\accumulation_tree
    copying accumulation_tree\abctree.py -> build\lib.win-amd64-3.6\accumulation_tree
    copying accumulation_tree\treeslice.py -> build\lib.win-amd64-3.6\accumulation_tree
    copying accumulation_tree\__init__.py -> build\lib.win-amd64-3.6\accumulation_tree
    running build_ext
    skipping 'accumulation_tree\accumulation_tree.c' Cython extension (up-to-date)
    building 'accumulation_tree.accumulation_tree' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

ERROR: Command errored out with exit status 1: 'C:\Users\IPL\anaconda3\envs\flare_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\IPL\\AppData\\Local\\Temp\\pip-install-swpip_rv\\accumulation-tree\\setup.py'"'"'; __file__='"'"'C:\\Users\\IPL\\AppData\\Local\\Temp\\pip-install-swpip_rv\\accumulation-tree\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\IPL\AppData\Local\Temp\pip-record-67vct1pd\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\IPL\anaconda3\envs\flare_env\Include\accumulation-tree' Check the logs for full command output.
`

**Comment by tkluck** [comment]
Going to close this one but maybe this message in the logs helps you debug it:
```
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
```
